//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LIBRARYEntities : DbContext
    {
        public LIBRARYEntities()
            : base("name=LIBRARYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADVERTISEMENT> ADVERTISEMENT { get; set; }
        public virtual DbSet<BASKETS> BASKETS { get; set; }
        public virtual DbSet<BOOKS> BOOKS { get; set; }
        public virtual DbSet<GENRES> GENRES { get; set; }
        public virtual DbSet<MARKS> MARKS { get; set; }
        public virtual DbSet<SUBSCRIPTIONS> SUBSCRIPTIONS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<YOUR_BOOKS> YOUR_BOOKS { get; set; }
    }
}
