//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARKS
    {
        public int MARK_ID { get; set; }
        public Nullable<int> BOOK_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> MARK { get; set; }
    
        public virtual BOOKS BOOKS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
